# Skill-Spec: Document Generator
# Version: 1.1.0
# Chinese language skill demonstrating multi-language support and v1.1 features

spec_version: "skill-spec/1.1"

_meta:
  content_language: "zh"
  mixed_language_strategy: "zh-primary"
  format: "full"
  token_budget: 400  # Target word count for SKILL.md

skill:
  name: "document-generator"
  version: "1.1.0"
  purpose: "根据代码、API 规范或设计文档自动生成技术文档"
  owner: "documentation-team"

  # v1.1: Enhanced metadata
  category: "documentation"
  complexity: "standard"
  tools_required:
    - Read
    - Write
    - Grep
    - Glob
  personas:
    - developer
    - technical-writer

# v1.1: Triggers (Superpowers-style)
triggers:
  use_when:
    - "用户请求生成 README 文档"
    - "代码库缺少技术文档"
    - "API 接口发生变更需要更新文档"
    - "准备发布新版本需要变更日志"
    - "新项目初始化后需要基础文档"
  do_not_use_when:
    - "翻译已存在的文档到其他语言"
    - "创建营销或销售文档"
    - "编写用户界面文本或 UI copy"
    - "生成法律或合规相关文档"

inputs:
  - name: source_content
    type: string
    required: true
    constraints: [not_empty, max_length_100000]
    description: "源代码或规范内容，用于生成文档"
    tags: ["content:code", "content:config"]

  - name: source_type
    type: string
    required: true
    description: "源内容的类型"
    domain:
      type: enum
      values: ["code", "api_spec", "design_doc", "changelog"]

  - name: doc_type
    type: string
    required: true
    description: "要生成的文档类型"
    domain:
      type: enum
      values: ["api_reference", "user_guide", "readme", "changelog", "architecture"]

  - name: output_language
    type: string
    required: false
    description: "输出文档的语言"
    domain:
      type: enum
      values: ["zh", "en", "zh-en"]
    default: "zh"

  - name: include_examples
    type: boolean
    required: false
    description: "是否在文档中包含示例代码"
    default: true

  - name: detail_level
    type: string
    required: false
    description: "文档详细程度"
    domain:
      type: enum
      values: ["brief", "standard", "detailed"]
    default: "standard"

preconditions:
  - "源内容必须是有效的文本格式"
  - "对于代码源，必须能够识别编程语言"
  - "对于 API 规范，必须是有效的 OpenAPI 或类似格式"

non_goals:
  - "翻译已存在的文档"
  - "生成市场营销或销售文档"
  - "创建法律或合规文档"
  - "生成用户界面文本"

# v1.1: Boundaries (SuperClaude-style)
boundaries:
  will:
    - "从代码注释和 docstring 中提取文档"
    - "生成 Markdown 格式的输出"
    - "支持中英文双语输出"
    - "根据源内容结构自动组织文档章节"
    - "添加示例代码（如果源内容中有）"
  will_not:
    - "在不同语言之间翻译已有文档"
    - "创建营销或促销内容"
    - "推断未在源代码中记录的行为"
    - "生成超出技术文档范围的内容"
    - "修改或重构源代码"

decision_rules:
  _config:
    match_strategy: first_match
    conflict_resolution: error

  rules:
    - id: rule_api_reference
      when: "doc_type == 'api_reference'"
      then:
        status: success
        path: api_reference_generation
        action: "生成 API 参考文档，包含端点、参数和响应说明"

    - id: rule_user_guide
      when: "doc_type == 'user_guide'"
      then:
        status: success
        path: user_guide_generation
        action: "生成用户指南，包含安装、配置和使用说明"

    - id: rule_readme
      when: "doc_type == 'readme'"
      then:
        status: success
        path: readme_generation
        action: "生成 README 文件，包含项目概述和快速开始指南"

    - id: rule_changelog
      when: "doc_type == 'changelog'"
      then:
        status: success
        path: changelog_generation
        action: "生成变更日志，按版本组织变更内容"

    - id: rule_architecture
      when: "doc_type == 'architecture'"
      then:
        status: success
        path: architecture_generation
        action: "生成架构文档，包含系统设计和组件说明"

    - id: rule_default
      is_default: true
      when: true
      then:
        status: error
        code: UNSUPPORTED_DOC_TYPE

steps:
  - id: parse_source
    action: "解析源内容，提取结构化信息"
    output: parsed_content

  - id: analyze_structure
    action: "分析内容结构，确定文档大纲"
    output: doc_outline
    based_on: [parsed_content]

  - id: extract_metadata
    action: "提取元数据（版本、作者、日期等）"
    output: metadata
    based_on: [parsed_content]

  - id: generate_sections
    action: "生成各个文档章节"
    output: doc_sections
    based_on: [doc_outline]

  - id: add_examples
    action: "添加示例代码和使用案例"
    output: examples
    condition: "include_examples == true"

  - id: apply_formatting
    action: "应用 Markdown 格式和样式"
    output: formatted_doc
    based_on: [doc_sections, examples]

  - id: translate_if_needed
    action: "如需要，进行语言翻译或双语处理"
    output: final_doc
    condition: "output_language == 'zh-en'"

# v1.1: Behavioral Flow (SuperClaude-style)
behavioral_flow:
  - phase: analyze
    description: "解析源内容，识别结构和关键信息"
    key_actions:
      - "检测编程语言或规范格式"
      - "提取注释、docstring 和文档块"
      - "识别 API 签名、函数参数、返回值"
      - "分析代码结构和模块关系"

  - phase: generate
    description: "根据分析结果生成文档内容"
    key_actions:
      - "创建文档大纲和章节结构"
      - "为每个章节生成内容"
      - "添加代码示例和使用说明"
      - "应用 Markdown 格式化"

  - phase: validate
    description: "校验生成结果的完整性和准确性"
    key_actions:
      - "检查所有必要章节是否存在"
      - "验证代码示例的语法正确性"
      - "确认链接和引用的有效性"
      - "检查格式一致性"

output_contract:
  format: json
  schema:
    type: object
    required: [status, document]
    properties:
      status:
        type: string
        enum: [success, partial, error]
      document:
        type: object
        required: [content, format]
        properties:
          title:
            type: string
          content:
            type: string
            description: "生成的 Markdown 文档内容"
          format:
            type: string
            enum: [markdown, html]
          sections:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                level:
                  type: integer
          word_count:
            type: integer
      warnings:
        type: array
        items:
          type: string
      metadata:
        type: object
        properties:
          generation_time_ms:
            type: integer
          source_type:
            type: string

failure_modes:
  - code: PARSE_ERROR
    retryable: false
    description: "无法解析源内容"

  - code: UNSUPPORTED_DOC_TYPE
    retryable: false
    description: "不支持的文档类型"

  - code: GENERATION_FAILED
    retryable: true
    description: "文档生成过程中发生错误"

  - code: TRANSLATION_ERROR
    retryable: true
    description: "双语翻译过程中发生错误"

edge_cases:
  - case: empty_source
    input:
      source_content: ""
      source_type: "code"
      doc_type: "readme"
    expected:
      status: error
      code: PARSE_ERROR

  - case: minimal_source
    description: "源内容信息量极少"
    input:
      source_content: "# placeholder"
      source_type: "code"
      doc_type: "readme"
    expected:
      status: partial
      warnings: ["源内容信息不足，部分章节为模板内容"]

  - case: mixed_language_source
    description: "源代码包含中英文混合注释"
    input:
      source_type: "code"
      output_language: "zh-en"
    expected:
      status: success

  - case: no_examples_available
    description: "无法从源内容中提取示例"
    input:
      include_examples: true
    expected:
      status: partial
      warnings: ["无法提取示例代码"]

# v1.1: Anti-patterns and Rationalizations (Superpowers-style)
anti_patterns:
  mistakes:
    - pattern: "直接复制粘贴源代码作为文档内容"
      why_bad: "用户需要的是解释和说明，不是代码副本"
      correct: "提取关键信息，用自然语言描述功能和用法"

    - pattern: "跳过解析阶段直接生成文档"
      why_bad: "没有分析就无法准确理解源内容结构"
      correct: "始终先完成 analyze 阶段，再进行 generate"

    - pattern: "生成文档后不进行验证"
      why_bad: "可能包含错误的示例或断开的链接"
      correct: "完成 validate 阶段，确保文档质量"

  rationalizations:
    - excuse: "这个功能太简单，不需要文档"
      reality: "简单功能的文档最容易编写和维护，跳过会导致后续更大的文档债务"

    - excuse: "等功能稳定后再写文档"
      reality: "文档与代码同步编写才能保持准确性，事后补写往往遗漏细节"

    - excuse: "代码是自文档化的，不需要额外文档"
      reality: "代码解释 HOW（如何实现），文档解释 WHY（为什么）和 WHEN（何时使用）"

    - excuse: "用户可以直接看源码"
      reality: "并非所有用户都有能力或时间阅读源码，文档降低了使用门槛"

  red_flags:
    - "在没有源代码的情况下尝试生成文档"
    - "跳过 analyze 阶段直接生成"
    - "生成的文档未经 validate 阶段就发布"
    - "生成的文档与源代码版本不匹配"
    - "忽略生成过程中的警告信息"

context:
  works_with:
    - skill: "code-analyzer"
      reason: "先分析代码结构，再生成文档"
    - skill: "markdown-formatter"
      reason: "美化和格式化生成的文档"
    - skill: "extract-api-contract"
      reason: "提取 API 规范作为文档生成的输入"

  prerequisites:
    - "对于代码文档，需要源代码具有基本的注释"
    - "对于 API 文档，需要有效的 API 规范文件"

  scenarios:
    - name: "新项目 README 生成"
      trigger: "项目初始化完成后，用户请求生成基础文档"
      description: "为新创建的项目生成包含概述、安装说明和快速开始的 README"

    - name: "API 文档更新"
      trigger: "API 接口发生变更时"
      description: "根据更新后的 API 规范重新生成参考文档"

    - name: "版本发布文档"
      trigger: "准备发布新版本时"
      description: "生成包含变更日志和升级指南的发布文档"

examples:
  - name: "生成简单 README"
    scenario: "新项目初始化后需要基础文档"
    trigger: "用户输入: 为这个 Python 项目生成 README"
    input:
      source_content: |
        def hello(name: str) -> str:
            """向用户问好。

            Args:
                name: 用户名称

            Returns:
                问候语字符串
            """
            return f"你好，{name}！"
      source_type: "code"
      doc_type: "readme"
      output_language: "zh"
      detail_level: "brief"
    output:
      status: success
      document:
        title: "项目文档"
        content: |
          # 项目文档

          ## 功能说明

          提供用户问候功能。

          ## 使用方法

          ```python
          result = hello("世界")
          # 输出: 你好，世界！
          ```
        format: "markdown"
    explanation: "从简单的 Python 函数生成基础 README 文档，包含功能说明和使用示例"
